spring:
  application:
    name: e-commerce
  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce
    username: root
    password: 240604
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
  servlet:
    context-path: /e-commerce

media:
  cloudinary:
    cloudName: ${MEDIA_CLOUDINARY_CLOUD_NAME}
    apiKey: ${MEDIA_CLOUDINARY_API_KEY}
    apiSecret: ${MEDIA_CLOUDINARY_API_SECRET}